# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do

  desc "Build for AppStore submission"
  lane :build_appstore do
    gym(
      output_directory: "build_AppStore",
      export_method: "app-store"
    )
  end

  desc "Use swiftlint to check source quality and apply small fixes (`autocorrect` mode)"
  lane :lint do
    swiftlint(
      mode: :autocorrect,
      config_file: ".swiftlint.yml",
      output_file: "./fastlane/swiftlintOutput.txt",
      ignore_exit_status: false
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    lint # run swiftlint
    # run tests
    scan(
      scheme: "Swiss-Birds"
    )

    build_appstore
    upload_to_testflight
  end

  desc "Build the app for screenshots creation and multiple installations from the same `build_Testing` location."
  lane :prepare_testing_build do
    scan(
      scheme: "Snapshots",
      derived_data_path: "build_Testing",
      build_for_testing: true,
      clean: true,
      device: "iPhone 12"
    )
  end

  desc "Create screenshots for all configured languages and devices (based on `prepare_testing_build` lane) and frame them using a silver frame (if available)"
  lane :take_screenshots do
    snapshot(
      scheme: "Snapshots",
      test_without_building: true,
      derived_data_path: "build_Testing",
    )
    frameit() 
  end
end
